version: '3'

services:
  apache:
    env_file:
      - .env
    container_name: ${PROJECT_NAME}_apache
    build:
      context: ./docker/apache
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=${WEB_DOCUMENT_ROOT}
    ports:
      - ${APP_PORT}:80
    links:
      - db
    depends_on:
      - db

  db:
    env_file:
      - .env
    container_name: ${PROJECT_NAME}_mysql
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  phpmyadmin:
    env_file:
      - .env
    container_name: ${PROJECT_NAME}_phpmyadmin
    build:
      context: ./docker/phpmyadmin
    ports:
      - 8081:80
    links:
      - db
    depends_on:
      - db
    environment:
      - PMA_HOST=${DB_NAME}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - UPLOAD_LIMIT=128M
